### ISSUE TITLE
Cant save the output to a file

### ISSUE THREAD

**Issue by zakuraxp** [Zierax/GoogleDorker#1]
i have read to save the output it needs to be using this --save command. But when i use it shows this error
![image](https://github.com/user-attachments/assets/8b352053-4ffb-4efa-a891-fe9706532834)

or
did i specified it wrong?

**Comment by Zierax** [comment]
i will look in it now

**Comment by Zierax** [comment]
i deleted --save and you can now use output as primary saving function 
i hope a good experience
